import { test, expect } from "@playwright/test";
import { gotoHome, loadSample, analyzeCounts, showView, park } from "./helpers.js";

/**
 * These run in demo mode, where there is no LLM connection and the assist tabs
 * serve pre-set example suggestions. That is deliberate: it exercises the
 * suggestion plumbing — render, accept, land in state — without a network call
 * or an API key, which is what makes it safe to run in CI.
 */
test.describe("Assist workflow", () => {
  test.beforeEach(async ({ page }) => {
    await gotoHome(page);
    await loadSample(page);
    await showView(page, "Assist");
  });

  test("starting the workflow produces suggestions", async ({ page }) => {
    await page.getByRole("button", { name: /Start Workflow/ }).click();
    await park(page);

    await expect(page.locator("text=/Elicit Judgments/").first()).toBeVisible();
    await expect(page.locator("text=/AI-generated by/").first()).toBeVisible();
    await expect(page.getByRole("button", { name: /Stop Workflow/ })).toBeVisible();
  });

  test("accepting a suggestion adds it to the process", async ({ page }) => {
    await page.getByRole("button", { name: /Start Workflow/ }).click();
    await expect(page.locator("text=/Elicit Judgments/").first()).toBeVisible();

    const before = (await analyzeCounts(page)).J;
    await showView(page, "Assist");

    // Accept is the first of the three round icon buttons on a suggestion row.
    // They carry no accessible name yet (see known-issues.spec.js), so they
    // have to be found structurally rather than by role name.
    const accepted = await page.evaluate(() => {
      const button = [...document.querySelectorAll("button")].find(
        (b) =>
          b.offsetWidth > 0 && b.offsetWidth <= 28 && !b.textContent.trim() && b.querySelector("svg"),
      );
      if (!button) return false;
      button.click();
      return true;
    });
    expect(accepted, "no suggestion accept control found").toBe(true);

    await expect.poll(async () => (await analyzeCounts(page)).J).toBe(before + 1);
  });

  test("the add bar arrives on the tab set to add a judgment", async ({ page }) => {
    // One strip under every tab now, rather than a cut-down panel per assist
    // tab — so what says this one is for judgments is the type it opens on.
    await page.getByRole("button", { name: /Start Workflow/ }).click();
    await expect(page.locator("text=/Elicit Judgments/").first()).toBeVisible();

    const bar = page.locator('[data-tutorial="add-bar"]');
    await expect(bar).toBeVisible();
    await expect(bar.getByRole("combobox", { name: "Element type" })).toHaveText(
      /Judgment/,
    );

    const add = bar.getByRole("button", { name: "Add element" });
    await expect(add).toBeDisabled();

    await bar.locator('textarea[placeholder*="Enter statement"]').fill("A typed judgment.");
    await expect(add).toBeEnabled();
  });
});
