import { test, expect } from "@playwright/test";
import { gotoHome, loadSample, showView, park, openMenu } from "./helpers.js";

/**
 * Demo mode, so the Review tab serves the pre-set example reading rather than
 * calling out — the same arrangement assist.spec.js relies on, and what makes
 * this safe to run in CI without a key.
 *
 * The sample ships with nothing accepted, so the series the feature exists for
 * is built up here the way a visitor builds it: run, accept, run again.
 */
/** Build up a two-review series the way a visitor does: run, accept, repeat. */
async function acceptTwo(page) {
  await page.getByRole("button", { name: /Analyse/ }).click();
  await park(page);
  await page.getByRole("button", { name: /Accept/i }).first().click();
  await expect(page.locator("text=/Saved reviews · 1/")).toBeVisible();

  await page.getByRole("button", { name: /Analyse again/ }).click();
  await park(page);
  await page.getByRole("button", { name: /Accept/i }).first().click();
  await expect(page.locator("text=/Saved reviews · 2/")).toBeVisible();
}

test.describe("Process review", () => {
  test.beforeEach(async ({ page }) => {
    await gotoHome(page);
    await loadSample(page);
    await showView(page, "Assist");
    await page.locator('button:text-is("Review")').click();
    await park(page);
  });

  test("opens with nothing accepted", async ({ page }) => {
    // Nothing may look accepted that the visitor did not accept — which is also
    // what stops a rejected candidate leaving a review behind in the list.
    await expect(page.locator("text=/Ask for a reading of the process/")).toBeVisible();
    await expect(page.locator("text=/Saved reviews/")).toHaveCount(0);
  });

  test("asks for nothing until the button is pressed", async ({ page }) => {
    // The run button carries the disclosure that this sends the process to an
    // LLM, so nothing may be fetched merely by opening the tab. Checked on the
    // word count, which only the pending candidate carries.
    await expect(page.getByRole("button", { name: /Analyse/ })).toBeVisible();
    await expect(page.locator("text=/Ask for a reading of the process/")).toBeVisible();
    await expect(page.locator("text=/\\d+ words/")).toHaveCount(0);
  });

  test("rejecting a review leaves nothing behind, before or after a reload", async ({
    page,
  }) => {
    // The reported bug: reject, and a review was still listed as saved. It was
    // the one seeded into the sample state, and reloading the demo brought it
    // back — the sample is deliberately never autosaved.
    await page.getByRole("button", { name: /Analyse/ }).click();
    await park(page);
    await page.getByRole("button", { name: /Reject/i }).first().click();
    await park(page);

    await expect(page.locator("text=/Saved reviews/")).toHaveCount(0);

    await page.reload();
    await loadSample(page);
    await showView(page, "Assist");
    await page.locator('button:text-is("Review")').click();
    await park(page);

    await expect(page.locator("text=/Saved reviews/")).toHaveCount(0);
  });

  test("a second run picks up the first", async ({ page }) => {
    // The series is the whole point of accumulating, so the demo has to show a
    // reading written with an earlier one in hand.
    await page.getByRole("button", { name: /Analyse/ }).click();
    await park(page);
    const first = await page.locator("text=/\\d+ words/").first().textContent();
    expect(first).toBeTruthy();
    await page.getByRole("button", { name: /Accept/i }).first().click();
    await expect(page.locator("text=/Saved reviews · 1/")).toBeVisible();

    await page.getByRole("button", { name: /Analyse again/ }).click();
    await park(page);

    await expect(
      page.locator("text=/previous review/").first(),
    ).toBeVisible();
  });

  test("analysing produces all five parts, and accepting keeps them", async ({
    page,
  }) => {
    await page.getByRole("button", { name: /Analyse/ }).click();
    await park(page);

    await expect(page.locator("text=/AI-generated by/").first()).toBeVisible();
    for (const heading of [
      "How the position moved",
      "Surprising turns",
      "Missed opportunities",
      "How the process was conducted",
    ]) {
      await expect(page.locator(`text=/${heading}/`).first()).toBeVisible();
    }
    await expect(page.locator("text=/\\d+ words/").first()).toBeVisible();

    // Accept is the first of the small round icon buttons on the card; they are
    // named only through their tooltips, so match on the accessible name.
    await page.getByRole("button", { name: /Accept/i }).first().click();
    await park(page);

    await expect(page.locator("text=/Saved reviews · 1/")).toBeVisible();
  });

  test("a discarded review leaves the rest of the series", async ({ page }) => {
    await acceptTwo(page);

    await page
      .getByRole("button", { name: /Discard this review/ })
      .first()
      .click();
    await park(page);

    await expect(page.locator("text=/Saved reviews · 1/")).toBeVisible();
  });

  test("the export carries the reviews", async ({ page }) => {
    await acceptTwo(page);

    await openMenu(page);
    const [download] = await Promise.all([
      page.waitForEvent("download"),
      page.locator('button:text-is("Export")').click(),
    ]);
    const stream = await download.createReadStream();
    const markdown = (await stream.toArray()).join("");

    expect(markdown).toContain("## Process Reviews");
    // Oldest first, so a later review's back-references land after what they
    // refer to; two headings, one per accepted review.
    expect(markdown.match(/^### Round \d+ — /gm)).toHaveLength(2);
    expect(markdown).toContain("**How the position moved**");
    // And the machine-readable block, which is what makes it re-importable.
    const state = JSON.parse(markdown.split("```re-state\n")[1].split("\n```")[0]);
    expect(state.reviews).toHaveLength(2);
  });

  test("the guided workflow never routes through Review", async ({ page }) => {
    // Review is an assist tab but not a workflow phase. Stepping the whole loop
    // must never land on it — and must never fire its request, which has no
    // disclosure of its own once a workflow is driving.
    await page.getByRole("button", { name: /Start Workflow/ }).click();
    await park(page);

    for (let i = 0; i < 5; i++) {
      await expect(page.locator("text=/Review Process/")).toHaveCount(0);
      const next = page.getByRole("button", { name: /Next|Continue/ }).first();
      if (!(await next.isVisible().catch(() => false))) break;
      await next.click();
      await park(page);
    }
    await expect(page.locator("text=/Review Process/")).toHaveCount(0);
  });
});
