import { test, expect } from "@playwright/test";
import { gotoHome, loadSample, showView, park, openMenu } from "./helpers.js";

/**
 * Demo mode, so the Review tab serves the pre-set example reading rather than
 * calling out — the same arrangement assist.spec.js relies on, and what makes
 * this safe to run in CI without a key.
 *
 * The sample state ships with one already-accepted review taken at round 4, so
 * these also cover the case the feature exists for: a *series* of readings, each
 * one written with the earlier ones in hand.
 */
test.describe("Process review", () => {
  test.beforeEach(async ({ page }) => {
    await gotoHome(page);
    await loadSample(page);
    await showView(page, "Assist");
    await page.locator('button:text-is("Review")').click();
    await park(page);
  });

  test("opens on the review already saved with the sample", async ({ page }) => {
    await expect(page.locator("text=/Saved reviews/")).toBeVisible();
    // Stamped with the round it read, and with where the process has since got
    // to — the sample is at round 8.
    await expect(page.locator("text=/Round 4 of 8/")).toBeVisible();
  });

  test("asks for nothing until the button is pressed", async ({ page }) => {
    // The run button carries the disclosure that this sends the process to an
    // LLM, so nothing may be fetched merely by opening the tab.
    //
    // Checked on the word count, which only the pending candidate carries. The
    // AI-generated line is no use here: the saved reviews are attributed too, so
    // asserting its absence passes whether or not the panel has even rendered.
    await expect(page.getByRole("button", { name: /Analyse/ })).toBeVisible();
    await expect(page.locator("text=/Saved reviews/")).toBeVisible();
    await expect(page.locator("text=/\\d+ words/")).toHaveCount(0);
  });

  test("analysing produces all five parts, and accepting keeps them", async ({
    page,
  }) => {
    await page.getByRole("button", { name: /Analyse/ }).click();
    await park(page);

    await expect(page.locator("text=/AI-generated by/").first()).toBeVisible();
    for (const heading of [
      "How the position moved",
      "Surprising turns",
      "Missed opportunities",
      "How the process was conducted",
    ]) {
      await expect(page.locator(`text=/${heading}/`).first()).toBeVisible();
    }
    await expect(page.locator("text=/\\d+ words/").first()).toBeVisible();

    // Accept is the first of the small round icon buttons on the card; they are
    // named only through their tooltips, so match on the accessible name.
    await page.getByRole("button", { name: /Accept/i }).first().click();
    await park(page);

    await expect(page.locator("text=/Saved reviews · 2/")).toBeVisible();
  });

  test("rejecting keeps nothing", async ({ page }) => {
    await page.getByRole("button", { name: /Analyse/ }).click();
    await park(page);
    await page.getByRole("button", { name: /Reject/i }).first().click();
    await park(page);

    await expect(page.locator("text=/Saved reviews · 1/")).toBeVisible();
  });

  test("a discarded review leaves the rest of the series", async ({ page }) => {
    await page.getByRole("button", { name: /Analyse/ }).click();
    await park(page);
    await page.getByRole("button", { name: /Accept/i }).first().click();
    await expect(page.locator("text=/Saved reviews · 2/")).toBeVisible();

    await page
      .getByRole("button", { name: /Discard this review/ })
      .first()
      .click();
    await park(page);

    await expect(page.locator("text=/Saved reviews · 1/")).toBeVisible();
  });

  test("the export carries the reviews", async ({ page }) => {
    await page.getByRole("button", { name: /Analyse/ }).click();
    await park(page);
    await page.getByRole("button", { name: /Accept/i }).first().click();
    await expect(page.locator("text=/Saved reviews · 2/")).toBeVisible();

    await openMenu(page);
    const [download] = await Promise.all([
      page.waitForEvent("download"),
      page.locator('button:text-is("Export")').click(),
    ]);
    const stream = await download.createReadStream();
    const markdown = (await stream.toArray()).join("");

    expect(markdown).toContain("## Process Reviews");
    // Oldest first, so a later review's back-references land after what they
    // refer to; two headings, one per accepted review.
    expect(markdown.match(/^### Round \d+ — /gm)).toHaveLength(2);
    expect(markdown).toContain("**How the position moved**");
    // And the machine-readable block, which is what makes it re-importable.
    const state = JSON.parse(markdown.split("```re-state\n")[1].split("\n```")[0]);
    expect(state.reviews).toHaveLength(2);
  });

  test("the guided workflow never routes through Review", async ({ page }) => {
    // Review is an assist tab but not a workflow phase. Stepping the whole loop
    // must never land on it — and must never fire its request, which has no
    // disclosure of its own once a workflow is driving.
    await page.getByRole("button", { name: /Start Workflow/ }).click();
    await park(page);

    for (let i = 0; i < 5; i++) {
      await expect(page.locator("text=/Review Process/")).toHaveCount(0);
      const next = page.getByRole("button", { name: /Next|Continue/ }).first();
      if (!(await next.isVisible().catch(() => false))) break;
      await next.click();
      await park(page);
    }
    await expect(page.locator("text=/Review Process/")).toHaveCount(0);
  });
});
