// @vitest-environment jsdom
//
// Renders the real ProcessReviewTab with the client mocked, so the accept /
// reject / modify decisions and the saved-review list can be exercised without
// the network. The provenance stamp is the load-bearing assertion here: a review
// the user reworded before accepting must not be attributed to the model alone.
import { vi, describe, it, expect, afterEach } from "vitest";
import { render, screen, fireEvent, cleanup, act } from "@testing-library/react";

vi.mock("../../utils/reviewClient.js", () => ({
  fetchProcessReview: vi.fn().mockResolvedValue({
    model: "test-model",
    suggestions: [
      {
        headline: "The centre moved.",
        arc: "ARC TEXT",
        surprises: "SURPRISES TEXT",
        missed: "MISSED TEXT",
        method: "METHOD TEXT",
      },
    ],
  }),
}));

import { ProcessReviewTab } from "./ProcessReviewTab.jsx";
import { fetchProcessReview } from "../../utils/reviewClient.js";

afterEach(() => {
  cleanup();
  vi.clearAllMocks();
});

const aState = (overrides = {}) => ({
  topic: "t",
  round: 4,
  elements: [],
  relations: [],
  coherence: {},
  log: [{ round: 1 }, { round: 2 }],
  ...overrides,
});

const savedReview = (overrides = {}) => ({
  id: "rev-1",
  round: 2,
  headline: "An earlier reading.",
  arc: "EARLIER ARC",
  surprises: "EARLIER SURPRISES",
  missed: "EARLIER MISSED",
  method: "EARLIER METHOD",
  model: "test-model",
  origin: "test-model",
  ...overrides,
});

function renderTab(props = {}) {
  const onSaveReview = vi.fn();
  const onDiscardReview = vi.fn();
  const utils = render(
    <ProcessReviewTab
      state={aState()}
      onSaveReview={onSaveReview}
      onDiscardReview={onDiscardReview}
      {...props}
    />,
  );
  return { ...utils, onSaveReview, onDiscardReview };
}

const analyse = async () => {
  await act(async () => {
    fireEvent.click(screen.getByRole("button", { name: /Analyse/ }));
  });
};

// ─── Asking for one ───────────────────────────────────────────────────────────

describe("asking for a review", () => {
  it("asks for nothing until the button is pressed", () => {
    // Unlike the workflow tabs there is no autoFetch here, and there must not
    // be: the run button carries the disclosure that this sends state to an LLM.
    renderTab();
    expect(fetchProcessReview).not.toHaveBeenCalled();
  });

  it("is disabled until the process has some rounds behind it", () => {
    renderTab({ state: aState({ log: [{ round: 1 }] }) });
    expect(screen.getByRole("button", { name: /Analyse/ }).disabled).toBe(true);
    expect(screen.getByText(/there has to be a process to read/)).toBeTruthy();
  });

  it("is disabled when there is no backend to ask", () => {
    renderTab({ suggestionsDisabled: true });
    expect(screen.getByRole("button", { name: /Analyse/ }).disabled).toBe(true);
  });

  it("renders all five parts and names the model", async () => {
    renderTab();
    await analyse();

    expect(screen.getByText("The centre moved.")).toBeTruthy();
    expect(screen.getByText("ARC TEXT")).toBeTruthy();
    expect(screen.getByText("SURPRISES TEXT")).toBeTruthy();
    expect(screen.getByText("MISSED TEXT")).toBeTruthy();
    expect(screen.getByText("METHOD TEXT")).toBeTruthy();
    expect(screen.getByText(/AI-generated by test-model/)).toBeTruthy();
  });

  it("counts the words against the target", async () => {
    renderTab();
    await analyse();
    // 3 (headline) + 2 + 2 + 2 + 2.
    expect(screen.getByText(/^11 words/)).toBeTruthy();
  });
});

// ─── Deciding about one ───────────────────────────────────────────────────────

describe("accepting, rejecting, and modifying", () => {
  it("saves the five parts and attributes them to the model", async () => {
    const { onSaveReview } = renderTab();
    await analyse();
    fireEvent.click(screen.getByRole("button", { name: /Accept/i }));

    expect(onSaveReview).toHaveBeenCalledWith({
      headline: "The centre moved.",
      arc: "ARC TEXT",
      surprises: "SURPRISES TEXT",
      missed: "MISSED TEXT",
      method: "METHOD TEXT",
      model: "test-model",
      origin: "test-model",
    });
  });

  it("clears the candidate once it has been accepted", async () => {
    renderTab();
    await analyse();
    fireEvent.click(screen.getByRole("button", { name: /Accept/i }));

    expect(screen.queryByText("ARC TEXT")).toBeNull();
  });

  it("saves nothing on reject", async () => {
    const { onSaveReview } = renderTab();
    await analyse();
    fireEvent.click(screen.getByRole("button", { name: /Reject/i }));

    expect(onSaveReview).not.toHaveBeenCalled();
    expect(screen.queryByText("ARC TEXT")).toBeNull();
  });

  it("marks an edited review as the user's as well as the model's", async () => {
    // The whole point of the origin field: a review the user reworded is not
    // attributable to the model alone, and the export prints this verbatim.
    const { onSaveReview } = renderTab();
    await analyse();
    fireEvent.click(screen.getByRole("button", { name: /Modify/i }));

    const arcBox = screen
      .getAllByRole("textbox")
      .find((el) => el.value === "ARC TEXT");
    fireEvent.change(arcBox, { target: { value: "MY OWN WORDING" } });
    fireEvent.click(screen.getByRole("button", { name: /Accept/i }));

    expect(onSaveReview).toHaveBeenCalledWith(
      expect.objectContaining({
        arc: "MY OWN WORDING",
        origin: "test-model & user",
      }),
    );
  });

  it("does not claim a user edit when the draft was left alone", async () => {
    const { onSaveReview } = renderTab();
    await analyse();
    fireEvent.click(screen.getByRole("button", { name: /Modify/i }));
    fireEvent.click(screen.getByRole("button", { name: /Accept/i }));

    expect(onSaveReview).toHaveBeenCalledWith(
      expect.objectContaining({ origin: "test-model" }),
    );
  });

  it("restores the model's wording when an edit is cancelled", async () => {
    renderTab();
    await analyse();
    fireEvent.click(screen.getByRole("button", { name: /Modify/i }));
    const arcBox = screen
      .getAllByRole("textbox")
      .find((el) => el.value === "ARC TEXT");
    fireEvent.change(arcBox, { target: { value: "SCRATCH" } });
    fireEvent.click(screen.getByRole("button", { name: /Cancel/i }));

    expect(screen.getByText("ARC TEXT")).toBeTruthy();
    expect(screen.queryByText("SCRATCH")).toBeNull();
  });
});

// ─── The saved series ─────────────────────────────────────────────────────────

describe("saved reviews", () => {
  it("opens the newest and leaves the rest closed", async () => {
    renderTab({
      state: aState({
        reviews: [
          savedReview({ id: "rev-1", headline: "Older.", arc: "OLDER ARC" }),
          savedReview({ id: "rev-2", headline: "Newer.", arc: "NEWER ARC" }),
        ],
      }),
    });

    expect(screen.getByText("NEWER ARC")).toBeTruthy();
    expect(screen.queryByText("OLDER ARC")).toBeNull();
  });

  it("lists the newest first while keeping the series oldest-first underneath", () => {
    const { container } = renderTab({
      state: aState({
        reviews: [
          savedReview({ id: "rev-1", headline: "Older." }),
          savedReview({ id: "rev-2", headline: "Newer." }),
        ],
      }),
    });
    const text = container.textContent;
    expect(text.indexOf("Newer.")).toBeLessThan(text.indexOf("Older."));
  });

  it("opens and closes one on click", () => {
    renderTab({
      state: aState({
        reviews: [savedReview({ headline: "Only.", arc: "ONLY ARC" })],
      }),
    });
    const toggle = screen.getByRole("button", { name: /Only\./ });

    expect(toggle.getAttribute("aria-expanded")).toBe("true");
    fireEvent.click(toggle);
    expect(toggle.getAttribute("aria-expanded")).toBe("false");
    expect(screen.queryByText("ONLY ARC")).toBeNull();
  });

  it("says which round a review covers once the process has moved past it", () => {
    // A review taken at round 2 is not a description of where things stand at
    // round 4, and the list is the only place that can say so.
    renderTab({ state: aState({ round: 4, reviews: [savedReview({ round: 2 })] }) });
    expect(screen.getByText(/Round 2 of 4/)).toBeTruthy();
  });

  it("discards by id", () => {
    const { onDiscardReview } = renderTab({
      state: aState({ reviews: [savedReview({ id: "rev-7" })] }),
    });
    fireEvent.click(screen.getByRole("button", { name: /Discard this review/ }));

    expect(onDiscardReview).toHaveBeenCalledWith("rev-7");
  });

  it("gives every button a name with a real word in it", async () => {
    // Same rule the app-wide audit applies: a glyph announces as "black
    // right-pointing triangle", so the icon-only controls here need labels.
    renderTab({ state: aState({ reviews: [savedReview()] }) });
    await analyse();

    const unnamed = [...document.querySelectorAll("button")]
      .map(
        (b) =>
          b.getAttribute("aria-label") ?? b.getAttribute("title") ?? b.textContent,
      )
      .filter((name) => !/[A-Za-z]{3,}/.test((name ?? "").trim()));
    expect(unnamed).toEqual([]);
  });
});
