// @vitest-environment jsdom
//
// The AI notice over an assist tab's suggestions, and the model named in the
// tab's header, for the two kinds of suggestion: recorded ones, which the demo
// shows without a model, and live ones.
import { describe, it, expect, afterEach } from "vitest";
import { render, screen, cleanup } from "@testing-library/react";

import { AiDisclosureBanner } from "./SuggestionActions.jsx";
import { SuggestionToolbar } from "./workflows/workflowComponents.jsx";
import { SampleSuggestionsContext } from "./sampleSuggestions.js";

afterEach(cleanup);

const withSamples = (sample, ui) =>
  render(
    <SampleSuggestionsContext.Provider value={sample}>
      {ui}
    </SampleSuggestionsContext.Provider>,
  );

const toolbar = (
  <SuggestionToolbar
    tab="elicitJudgments"
    title="Elicit Judgments"
    actionLabel="Elicit"
    rerunLabel="Elicit more"
    suggestionCount={3}
    loading={false}
    hasResult
    onRun={() => {}}
    model="claude-fable-5"
  />
);

describe("recorded suggestions", () => {
  it("say they were made when the demo was, not from this position", () => {
    withSamples(true, <AiDisclosureBanner model="claude-fable-5" />);
    expect(
      screen.getByText(
        /Pre-set: AI-generated by claude-fable-5 when this demo was made/,
      ),
    ).toBeTruthy();
    expect(screen.getByText(/not from the position on screen/)).toBeTruthy();
  });

  it("are marked pre-set beside the model's name in the header", () => {
    withSamples(true, toolbar);
    expect(screen.getByText(/· pre-set \(claude-fable-5\)/)).toBeTruthy();
  });
});

describe("live suggestions", () => {
  it("name the model that made them, and nothing about pre-set", () => {
    withSamples(false, <AiDisclosureBanner model="gpt-4o" />);
    expect(screen.getByText(/AI-generated by gpt-4o\./)).toBeTruthy();
    expect(screen.queryByText(/Pre-set/)).toBeNull();
  });

  it("show the model's name alone in the header", () => {
    withSamples(false, toolbar);
    expect(screen.getByText(/· claude-fable-5/)).toBeTruthy();
    expect(screen.queryByText(/pre-set/)).toBeNull();
  });
});
