"""
Pydantic models mirroring the RE state schema defined in app/src/types.js.

Keeping these in sync with the frontend schema is the contract between V1 and V2.
Files exported by the frontend (re-state JSON blocks) deserialise directly into
these models; the import security logic mirrors importMarkdown.js.
"""

from __future__ import annotations

from typing import Annotated, Any, Literal, Optional
from pydantic import BaseModel, Field


# ── Element ────────────────────────────────────────────────────────────────────

ElementType = Literal["judgment", "principle", "theory"]
Status = Literal["active", "revised", "withdrawn", "rejected", "possible"]
Confidence = Annotated[float, Field(ge=0.0, le=1.0)]


class REElement(BaseModel):
    """A single node in the RE graph — a judgment, principle, or background theory.

    ``id`` follows the ``J<n>`` / ``P<n>`` / ``T<n>`` convention.
    Revised elements carry ``previous_text`` and ``revised_round``;
    withdrawn or rejected elements carry ``reason`` / ``withdrawn_round`` /
    ``rejected_round`` as appropriate.
    """

    id: str = Field(pattern=r"^[JPT]\d+$")
    type: ElementType
    status: Status
    confidence: Confidence
    origin: str = Field(max_length=200, default="")
    text: str = Field(max_length=10_000)
    added_round: int = Field(alias="addedRound", ge=1)
    negated: Optional[bool] = False

    # Revised fields
    previous_text: Optional[str] = Field(None, alias="previousText", max_length=10_000)
    revised_round: Optional[int] = Field(None, alias="revisedRound", ge=1)

    # Withdrawn fields
    reason: Optional[str] = Field(None, max_length=2_000)
    withdrawn_round: Optional[int] = Field(None, alias="withdrawnRound", ge=1)

    # Rejected fields
    rejected_round: Optional[int] = Field(None, alias="rejectedRound", ge=1)

    # Questionnaire fields
    questionnaire_index: Optional[int] = Field(None, alias="questionnaireIndex", ge=0)

    model_config = {"populate_by_name": True}


# ── Relation ───────────────────────────────────────────────────────────────────

RelationType = Literal[
    "supports",
    "conflicts",
    "undermines",
    "depends",
    "entails",
    "jointly_entails",
    "precludes",
    "jointly_precludes",
]


class RERelation(BaseModel):
    """A directed edge between two RE elements.

    ``from_id`` / ``to_id`` use the JSON aliases ``from`` / ``to`` to match
    the frontend schema.  A single ordered pair can have multiple relations
    (e.g. one ``supports`` and one ``undermines`` entry recorded separately).

    ``argument_id`` is set only for ``(jointly) entails`` relations: all premises of the
    same detected argument share the same ``argument_id`` so the graph can
    visually group them.
    """

    from_id: str = Field(alias="from", pattern=r"^[JPT]\d+$")
    to_id: str = Field(alias="to", pattern=r"^[JPT]\d+$")
    type: RelationType
    explanation: str = Field(max_length=2_000, default="")
    added_round: int = Field(alias="addedRound", ge=1)
    argument_id: Optional[str] = Field(None, alias="argumentId", max_length=200)
    origin: Optional[str] = Field(None, max_length=200)

    status: Optional[Status] = None
    revised_round: Optional[int] = Field(None, alias="revisedRound", ge=1)
    withdrawn_round: Optional[int] = Field(None, alias="withdrawnRound", ge=1)
    rejected_round: Optional[int] = Field(None, alias="rejectedRound", ge=1)

    model_config = {"populate_by_name": True}


# ── Log ────────────────────────────────────────────────────────────────────────


class RELogEntry(BaseModel):
    """Structured record of what happened in a single RE round.

    ``findings`` summarises observed coherence issues; ``options`` lists
    the adjustment proposals considered; ``decision`` records what the user
    chose; ``changes`` describes the resulting state mutations.
    """

    round: int = Field(ge=1)
    findings: str = Field(max_length=5_000, default="")
    options: str = Field(max_length=5_000, default="")
    decision: str = Field(max_length=5_000, default="")
    changes: str = Field(max_length=5_000, default="")


# ── Coherence ──────────────────────────────────────────────────────────────────


class RECoherence(BaseModel):
    """Snapshot of the coherence analysis at the end of a review round.

    Each list contains human-readable strings generated by the coherence
    checker (or the LLM):
    - ``tensions`` — conflicting or undermining pairs that have not been resolved.
    - ``orphans``  — elements with no relations to any other element.
    - ``clusters`` — descriptive labels for each identified coherent cluster.
    """

    tensions: list[str] = Field(default_factory=list, max_length=200)
    orphans: list[str] = Field(default_factory=list, max_length=200)
    clusters: list[str] = Field(default_factory=list, max_length=200)


# ── State ──────────────────────────────────────────────────────────────────────


class REState(BaseModel):
    """Complete serialisable state of a wide reflective equilibrium process.

    This is the canonical wire format shared between the frontend (types.js)
    and the backend.  The frontend exports JSON blocks that deserialise
    directly into this model; the backend routers accept subsets of it.
    ``phase`` is always 2 for the standalone app (phase 1 is the Claude Skill).
    """

    topic: str = Field(max_length=500, default="")
    phase: int = Field(default=2, ge=1)
    round: int = Field(ge=1)
    model: Optional[Literal["questionnaire"]] = None
    elements: list[REElement] = Field(default_factory=list, max_length=1_000)
    relations: list[RERelation] = Field(default_factory=list, max_length=5_000)
    coherence: RECoherence = Field(default_factory=RECoherence)
    log: list[RELogEntry] = Field(default_factory=list, max_length=1_000)
    questionnaire_spec: Optional[Any] = Field(None, alias="questionnaireSpec")
